export const languages = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avar",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Cambodian",
  "Catalan",
  "Chamorro",
  "Chechen",
  "Chichewa",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi",
  "Dutch",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek",
  "Greenlandic",
  "Guarani",
  "Gujarati",
  "Haitian",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiak",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Kikuyu",
  "Kirghiz",
  "Kirundi",
  "Komi",
  "Kongo",
  "Korean",
  "Kuanyama",
  "Kurdish",
  "Laotian",
  "Latin",
  "Latvian",
  "Limburgian",
  "Lingala",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Moldovan",
  "Mongolian",
  "Nauruan",
  "Navajo",
  "Ndonga",
  "Nepali",
  "North Ndebele",
  "Norwegian",
  "Norwegian Nynorsk",
  "Occitan",
  "Ojibwa",
  "Old Church Slavonic / Old Bulgarian",
  "Oriya",
  "Oromo",
  "Ossetian",
  "Pali",
  "Pashto",
  "Persian",
  "Peul",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Quechua",
  "Raeto Romance",
  "Romanian",
  "Russian",
  "Rwandi",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Scottish Gaelic",
  "Serbian",
  "Serbo-Croatian",
  "Shona",
  "Sichuan Yi",
  "Sindhi",
  "Sinhalese",
  "Slovak",
  "Slovenian",
  "Somalia",
  "Southern Sotho",
  "South Ndebele",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "West Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang",
  "Zulu",
];

export const affiliation = [
  { label: "CA", value: "ca" },
  {
    label: "Student",
    value: "student",
    children: [
      {
        value: "2019",
        label: "2019",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
      {
        value: "2018",
        label: "2018",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
      {
        value: "2017",
        label: "2017",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
      {
        value: "2016",
        label: "2016",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
      {
        value: "2015",
        label: "2015",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
      {
        value: "2014",
        label: "2014",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
      {
        value: "2013",
        label: "2013",
        children: [
          { value: "spring", label: "Spring" },
          { value: "fall", label: "Fall" },
        ],
      },
    ],
  },
];
